import os 
from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
import random

app = FastAPI()

origins = os.environ.get("ALLOWED_ORIGINS", "*").split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

QUESTIONS_JA = {
    "easy": [
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>に<ruby>行<rt>い</rt></ruby>こう！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>へ<ruby>進<rt>すす</rt></ruby>もう！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>のほうが<ruby>安全<rt>あんぜん</rt></ruby>そうだ！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>に<ruby>何<rt>なに</rt></ruby>かがある<ruby>気<rt>き</rt></ruby>がする！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>のほうが<ruby>明<rt>あか</rt></ruby>るい！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>から<ruby>風<rt>かぜ</rt></ruby>が<ruby>吹<rt>ふ</rt></ruby>いてきた！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>へ<ruby>向<rt>む</rt></ruby>かって<ruby>進<rt>すす</rt></ruby>め！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>に<ruby>宝<rt>たから</rt></ruby>のにおいがする！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>空<rt>そら</rt></ruby>に<ruby>虹<rt>にじ</rt></ruby>が<ruby>見<rt>み</rt></ruby>える！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>に<ruby>島<rt>しま</rt></ruby>が<ruby>見<rt>み</rt></ruby>えた！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>に<ruby>海賊<rt>かいぞく</rt></ruby>がいないよ！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>にカモメが<ruby>飛<rt>と</rt></ruby>んでる！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の方から<ruby>音<rt>おと</rt></ruby>がする！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>が<ruby>何<rt>なに</rt></ruby>だか<ruby>気<rt>き</rt></ruby>になる…", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>のほうへ<ruby>行<rt>い</rt></ruby>こう！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>の<ruby>方<rt>ほう</rt></ruby>が<ruby>安心<rt>あんしん</rt></ruby>だよ！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>にキラキラした<ruby>光<rt>ひかり</rt></ruby>！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>の<ruby>方角<rt>ほうがく</rt></ruby>を見てごらん！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>に<ruby>向<rt>む</rt></ruby>かって<ruby>船<rt>ふね</rt></ruby>を<ruby>出<rt>だ</rt></ruby>そう！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>に<ruby>向<rt>む</rt></ruby>かって<ruby>風<rt>かぜ</rt></ruby>を読もう！", "correct": "left" },
    ],
    "normal": [
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>じゃない<ruby>方<rt>ほう</rt></ruby>へ<ruby>進<rt>すす</rt></ruby>もう！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>じゃない<ruby>方<rt>ほう</rt></ruby>に<ruby>宝<rt>たから</rt></ruby>があるぞ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>反対側<rt>はんたいがわ</rt></ruby>を<ruby>選<rt>えら</rt></ruby>ぼう！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>の逆にあるものを見に<ruby>行<rt>い</rt></ruby>こう！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>に<ruby>見<rt>み</rt></ruby>えるけど、あえて<ruby>左<rt>ひだり</rt></ruby>に<ruby>行<rt>い</rt></ruby>け！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>と<ruby>思<rt>おも</rt></ruby>わせて、<ruby>正解<rt>せいかい</rt></ruby>は<ruby>右<rt>みぎ</rt></ruby>だ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>方角<rt>ほうがく</rt></ruby>には<ruby>何<rt>なに</rt></ruby>もない！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>のほうが<ruby>危<rt>あぶ</rt></ruby>ない！<ruby>右<rt>みぎ</rt></ruby>に<ruby>進<rt>すす</rt></ruby>もう！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>が<ruby>正<rt>ただ</rt></ruby>しいとは<ruby>限<rt>かぎ</rt></ruby>らない…<ruby>左<rt>ひだり</rt></ruby>へ！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>は<ruby>罠<rt>わな</rt></ruby>かも？<ruby>右<rt>みぎ</rt></ruby>を<ruby>選<rt>えら</rt></ruby>ぼう！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>には<ruby>誰<rt>だれ</rt></ruby>もいない！じゃあ…？", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>が<ruby>正<rt>ただ</rt></ruby>しいと<ruby>信<rt>しん</rt></ruby>じて！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>方<rt>ほう</rt></ruby>に<ruby>勇者<rt>ゆうしゃ</rt></ruby>の<ruby>足跡<rt>あしあと</rt></ruby>が！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>の<ruby>方角<rt>ほうがく</rt></ruby>に<ruby>光<rt>ひかり</rt></ruby>が<ruby>差<rt>さ</rt></ruby>している！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>と<ruby>左<rt>ひだり</rt></ruby>、<ruby>今回<rt>こんかい</rt></ruby>は<ruby>右<rt>みぎ</rt></ruby>が<ruby>正解<rt>せいかい</rt></ruby>だ！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>と<ruby>右<rt>みぎ</rt></ruby>、<ruby>信<rt>しん</rt></ruby>じるなら<ruby>左<rt>ひだり</rt></ruby>を！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>方向<rt>ほうこう</rt></ruby>には<ruby>仲間<rt>なかま</rt></ruby>がいるぞ！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>の<ruby>向<rt>む</rt></ruby>こうに<ruby>島<rt>しま</rt></ruby>が<ruby>見<rt>み</rt></ruby>える！", "correct": "left" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>先<rt>さき</rt></ruby>に<ruby>宝箱<rt>たからばこ</rt></ruby>がある<ruby>気<rt>き</rt></ruby>がする！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>じゃない<ruby>方<rt>ほう</rt></ruby>が<ruby>安全<rt>あんぜん</rt></ruby>だ！", "correct": "right" },
    ],
    "hard": [
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>じゃない<ruby>方<rt>ほう</rt></ruby>へ<ruby>進<rt>すす</rt></ruby>め！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>と<ruby>見<rt>み</rt></ruby>せかけて<ruby>右<rt>みぎ</rt></ruby>！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>の<ruby>反対側<rt>はんたいがわ</rt></ruby>へ<ruby>進<rt>すす</rt></ruby>もう！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>が<ruby>罠<rt>わな</rt></ruby>だ、<ruby>右<rt>みぎ</rt></ruby>だ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>と<ruby>思<rt>おも</rt></ruby>わせて<ruby>左<rt>ひだり</rt></ruby>だ！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>に<ruby>見<rt>み</rt></ruby>えるが<ruby>進<rt>すす</rt></ruby>むのは<ruby>右<rt>みぎ</rt></ruby>！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>じゃない<ruby>方向<rt>ほうこう</rt></ruby>に<ruby>注意<rt>ちゅうい</rt></ruby>！", "correct": "right" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>を<ruby>信<rt>しん</rt></ruby>じるな！<ruby>右<rt>みぎ</rt></ruby>へ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>に<ruby>向<rt>む</rt></ruby>かうと危険！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>じゃない<ruby>道<rt>みち</rt></ruby>を<ruby>選<rt>えら</rt></ruby>ぼう！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>ではない、<ruby>左<rt>ひだり</rt></ruby>だ！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>ではない、<ruby>右<rt>みぎ</rt></ruby>だ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>を<ruby>選<rt>えら</rt></ruby>ぶと<ruby>戻<rt>もど</rt></ruby>ってしまう！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>はフェイクだ！<ruby>右<rt>みぎ</rt></ruby>に<ruby>行<rt>い</rt></ruby>け！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>は<ruby>行<rt>い</rt></ruby>き止まり！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>が<ruby>正解<rt>せいかい</rt></ruby>とは<ruby>限<rt>かぎ</rt></ruby>らないぞ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>のつもりが<ruby>左<rt>ひだり</rt></ruby>だった！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>っぽいが<ruby>右<rt>みぎ</rt></ruby>だ！", "correct": "right" },
        { "prompt": "<ruby>右<rt>みぎ</rt></ruby>を<ruby>疑<rt>うたが</rt></ruby>え、<ruby>左<rt>ひだり</rt></ruby>が<ruby>安全<rt>あんぜん</rt></ruby>！", "correct": "left" },
        { "prompt": "<ruby>左<rt>ひだり</rt></ruby>が<ruby>怖<rt>こわ</rt></ruby>いなら<ruby>右<rt>みぎ</rt></ruby>へ！", "correct": "right" },
    ],
}

QUESTIONS_EN = {
    "easy": [
        { "prompt": "Let's go right!", "correct": "right" },
        { "prompt": "Head to the left!", "correct": "left" },
        { "prompt": "The right side looks safer!", "correct": "right" },
        { "prompt": "I feel like something's on the left!", "correct": "left" },
        { "prompt": "It’s brighter to the right!", "correct": "right" },
        { "prompt": "The wind is blowing from the left!", "correct": "left" },
        { "prompt": "Move forward to the right!", "correct": "right" },
        { "prompt": "Smells like treasure on the left!", "correct": "left" },
        { "prompt": "There’s a rainbow in the sky to the right!", "correct": "right" },
        { "prompt": "I see an island on the left!", "correct": "left" },
        { "prompt": "No pirates on the right side!", "correct": "right" },
        { "prompt": "A seagull is flying to the left!", "correct": "left" },
        { "prompt": "I hear a sound from the right!", "correct": "right" },
        { "prompt": "Something about the left seems curious...", "correct": "left" },
        { "prompt": "Let’s go toward the right!", "correct": "right" },
        { "prompt": "The left seems safer!", "correct": "left" },
        { "prompt": "There’s a sparkle of light on the right!", "correct": "right" },
        { "prompt": "Take a look to the left!", "correct": "left" },
        { "prompt": "Set sail toward the right!", "correct": "right" },
        { "prompt": "Read the wind and head left!", "correct": "left" },
    ],
    "normal": [
        { "prompt": "Go the opposite of right!", "correct": "left" },
        { "prompt": "The treasure is on the side that isn’t left!", "correct": "right" },
        { "prompt": "Choose the direction opposite of right!", "correct": "left" },
        { "prompt": "Let’s head to the opposite of left!", "correct": "right" },
        { "prompt": "You see right, but go left!", "correct": "left" },
        { "prompt": "It looks like left, but the answer is right!", "correct": "right" },
        { "prompt": "There’s nothing in the right direction!", "correct": "left" },
        { "prompt": "The left side is dangerous! Go right!", "correct": "right" },
        { "prompt": "Right isn’t always right… go left!", "correct": "left" },
        { "prompt": "Left might be a trap! Pick right!", "correct": "right" },
        { "prompt": "No one is on the right… so?", "correct": "left" },
        { "prompt": "Believe in the left!", "correct": "left" },
        { "prompt": "There are footprints to the right!", "correct": "right" },
        { "prompt": "Light shines from the left!", "correct": "left" },
        { "prompt": "Right or left? Right is the answer this time!", "correct": "right" },
        { "prompt": "Between left and right, trust left!", "correct": "left" },
        { "prompt": "Your allies are in the right direction!", "correct": "right" },
        { "prompt": "An island appears beyond the left!", "correct": "left" },
        { "prompt": "A treasure chest might be ahead to the right!", "correct": "right" },
        { "prompt": "The side that’s not left is safer!", "correct": "right" },
    ],
    "hard": [
        { "prompt": "Go in the direction that’s not right!", "correct": "left" },
        { "prompt": "Looks like left, but go right!", "correct": "right" },
        { "prompt": "Let’s head to the side opposite of right!", "correct": "left" },
        { "prompt": "Left is a trap—go right!", "correct": "right" },
        { "prompt": "You think it’s right, but it’s actually left!", "correct": "left" },
        { "prompt": "You see left, but move right!", "correct": "right" },
        { "prompt": "Watch out for the not-right direction!", "correct": "right" },
        { "prompt": "Don’t trust left—go right!", "correct": "right" },
        { "prompt": "It’s dangerous to go right!", "correct": "left" },
        { "prompt": "Pick the direction that isn’t left!", "correct": "right" },
        { "prompt": "It’s not right, so go left!", "correct": "left" },
        { "prompt": "It’s not left, so go right!", "correct": "right" },
        { "prompt": "If you choose right, you’ll go backwards!", "correct": "left" },
        { "prompt": "Left is a fake! Go right!", "correct": "right" },
        { "prompt": "Right is a dead end!", "correct": "left" },
        { "prompt": "Left may not be the right answer!", "correct": "right" },
        { "prompt": "You thought it was right, but it was left!", "correct": "left" },
        { "prompt": "Feels like left, but it’s right!", "correct": "right" },
        { "prompt": "Doubt right—left is safe!", "correct": "left" },
        { "prompt": "Scared of the left? Then go right!", "correct": "right" },
    ]
}


@app.get("/questions")
def get_questions(
    difficulty: str = Query(..., regex="^(easy|normal|hard)$"),
    language: str = Query("ja", regex="^(ja|en)$"),
):
    if language == "en":
        questions = QUESTIONS_EN.get(difficulty, [])
    else:
        questions = QUESTIONS_JA.get(difficulty, [])
    
    # 問題数制限
    limit = {"easy": 10, "normal": 15, "hard": 20}.get(difficulty, 10)

    questions_shuffled = questions[:]
    random.shuffle(questions_shuffled)

    return questions_shuffled[:limit]



FORTUNES_JA = [
    "<ruby>今日<rt>きょう</rt></ruby>、<ruby>臨時<rt>りんじ</rt></ruby><ruby>収入<rt>しゅうにゅう</rt></ruby>があるかも！",
    "あなたに<ruby>嬉<rt>うれ</rt></ruby>しい<ruby>知<rt>し</rt></ruby>らせが<ruby>届<rt>とど</rt></ruby>くよ",
    "<ruby>大切<rt>たいせつ</rt></ruby>な<ruby>人<rt>ひと</rt></ruby>と<ruby>素敵<rt>すてき</rt></ruby>な<ruby>時間<rt>じかん</rt></ruby>を<ruby>過<rt>すご</rt></ruby>せる！",
    "<ruby>願<rt>ねが</rt></ruby>いがひとつ<ruby>叶<rt>かな</rt></ruby>う<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>新<rt>あたら</rt></ruby>しい<ruby>出会<rt>であ</rt></ruby>いがあるかもね",
    "<ruby>運気<rt>うんき</rt></ruby>が<ruby>上昇<rt>じょうしょう</rt></ruby><ruby>中<rt>ちゅう</rt></ruby>！<ruby>何<rt>なに</rt></ruby><ruby>事<rt>ごと</rt></ruby>も<ruby>順調<rt>じゅんちょう</rt></ruby>に<ruby>進<rt>すす</rt></ruby>むよ",
    "<ruby>健康<rt>けんこう</rt></ruby>に<ruby>恵<rt>めぐ</rt></ruby>まれる<ruby>一日<rt>いちにち</rt></ruby>だよ",
    "<ruby>楽<rt>たの</rt></ruby>しいことがたくさん<ruby>訪<rt>おとず</rt></ruby>れるよ！",
    "<ruby>笑顔<rt>えがお</rt></ruby>が<ruby>絶<rt>た</rt></ruby>えない<ruby>日<rt>ひ</rt></ruby>になるよ",
    "<ruby>幸運<rt>こううん</rt></ruby>があなたを<ruby>見<rt>み</rt></ruby>つけるよ！",
    "<ruby>夢<rt>ゆめ</rt></ruby>に<ruby>近<rt>ちか</rt></ruby>づく<ruby>大<rt>おお</rt></ruby>チャンス！",
    "<ruby>心<rt>こころ</rt></ruby>が<ruby>穏<rt>おだ</rt></ruby>やかになる<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>思<rt>おも</rt></ruby>わぬ<ruby>幸運<rt>こううん</rt></ruby>が<ruby>舞<rt>ま</rt></ruby>い<ruby>込<rt>こ</rt></ruby>むかも！",
    "<ruby>願<rt>ねが</rt></ruby>いが<ruby>叶<rt>かな</rt></ruby>う<ruby>予感<rt>よかん</rt></ruby>がするよ",
    "<ruby>人間関係<rt>にんげんかんけい</rt></ruby>が<ruby>良好<rt>りょうこう</rt></ruby>になるよ",
    "<ruby>嬉<rt>うれ</rt></ruby>しいサプライズが<ruby>待<rt>ま</rt></ruby>っている！",
    "<ruby>金運<rt>きんうん</rt></ruby>がアップするよ！",
    "<ruby>努力<rt>どりょく</rt></ruby>が<ruby>報<rt>むく</rt></ruby>われる<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>感謝<rt>かんしゃ</rt></ruby>の<ruby>気持<rt>きも</rt></ruby>ちを<ruby>伝<rt>つた</rt></ruby>えると<ruby>良<rt>よ</rt></ruby>いよ",
    "<ruby>笑顔<rt>えがお</rt></ruby>があなたを<ruby>輝<rt>かがや</rt></ruby>かせるよ",
    "<ruby>新<rt>あたら</rt></ruby>しい<ruby>趣味<rt>しゅみ</rt></ruby>が<ruby>見<rt>み</rt></ruby>つかるかもね！",
    "チャレンジする<ruby>心<rt>こころ</rt></ruby>が<ruby>芽生<rt>めば</rt></ruby>える<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>心<rt>こころ</rt></ruby>が<ruby>軽<rt>かる</rt></ruby>くなる<ruby>出来事<rt>できごと</rt></ruby>があるよ",
    "<ruby>友達<rt>ともだち</rt></ruby>との<ruby>絆<rt>きずな</rt></ruby>が<ruby>深<rt>ふか</rt></ruby>まるよ！",
    "<ruby>愛情運<rt>あいじょううん</rt></ruby>が<ruby>良好<rt>りょうこう</rt></ruby>になるよ",
    "<ruby>夢<rt>ゆめ</rt></ruby>をあきらめないで<ruby>進<rt>すす</rt></ruby>もう！",
    "<ruby>幸<rt>しあわ</rt></ruby>せな<ruby>出来事<rt>できごと</rt></ruby>が<ruby>続<rt>つづ</rt></ruby>くよ",
    "ポジティブな<ruby>気持<rt>きも</rt></ruby>ちが<ruby>大切<rt>たいせつ</rt></ruby>だよ",
    "<ruby>良<rt>よ</rt></ruby>いニュースが<ruby>舞<rt>ま</rt></ruby>い<ruby>込<rt>こ</rt></ruby>むよ！",
    "<ruby>元気<rt>げんき</rt></ruby>いっぱいの<ruby>一日<rt>いちにち</rt></ruby>！",
    "チャンスを<ruby>掴<rt>つか</rt></ruby>む<ruby>大切<rt>たいせつ</rt></ruby>な<ruby>時<rt>とき</rt></ruby>だよ",
    "リラックスできる<ruby>時間<rt>じかん</rt></ruby>を<ruby>持<rt>も</rt></ruby>とう",
    "<ruby>幸<rt>しあわ</rt></ruby>せを<ruby>感<rt>かん</rt></ruby>じる<ruby>瞬間<rt>しゅんかん</rt></ruby>が<ruby>増<rt>ふ</rt></ruby>えるよ",
    "<ruby>願<rt>ねが</rt></ruby>い<ruby>事<rt>ごと</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>いやすい<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>心<rt>こころ</rt></ruby>の<ruby>成長<rt>せいちょう</rt></ruby>を<ruby>感<rt>かん</rt></ruby>じる<ruby>日<rt>ひ</rt></ruby>",
    "<ruby>笑顔<rt>えがお</rt></ruby>で<ruby>人<rt>ひと</rt></ruby>に<ruby>接<rt>せっ</rt></ruby>すると<ruby>良<rt>よ</rt></ruby>いよ",
    "<ruby>新<rt>あたら</rt></ruby>しい<ruby>学<rt>まな</rt></ruby>びがある<ruby>日<rt>ひ</rt></ruby>だよ！",
    "<ruby>素敵<rt>すてき</rt></ruby>な<ruby>人<rt>ひと</rt></ruby>との<ruby>出会<rt>であ</rt></ruby>いがあるよ",
    "<ruby>心<rt>こころ</rt></ruby>にゆとりができるよ",
    "<ruby>運命<rt>うんめい</rt></ruby>の<ruby>出会<rt>であ</rt></ruby>いが<ruby>近<rt>ちか</rt></ruby>いかも！",
    "やる<ruby>気<rt>き</rt></ruby>がみなぎる<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>嬉<rt>うれ</rt></ruby>しい<ruby>知<rt>し</rt></ruby>らせが<ruby>届<rt>とど</rt></ruby>くよ！",
    "<ruby>感謝<rt>かんしゃ</rt></ruby>の<ruby>気持<rt>きも</rt></ruby>ちを<ruby>忘<rt>わす</rt></ruby>れずにね",
    "<ruby>笑顔<rt>えがお</rt></ruby>が<ruby>幸運<rt>こううん</rt></ruby>を<ruby>呼<rt>よ</rt></ruby>ぶよ！",
    "<ruby>良運<rt>りょううん</rt></ruby>が<ruby>流<rt>なが</rt></ruby>れているよ",
    "<ruby>新<rt>あたら</rt></ruby>たな<ruby>挑戦<rt>ちょうせん</rt></ruby>が<ruby>成功<rt>せいこう</rt></ruby>するよ！",
    "<ruby>楽<rt>たの</rt></ruby>しい<ruby>行事<rt>ぎょうじ</rt></ruby>が<ruby>待<rt>ま</rt></ruby>っているよ！",
    "<ruby>幸運<rt>こううん</rt></ruby>があなたに<ruby>微笑<rt>ほほえ</rt></ruby>むよ",
    "<ruby>心<rt>こころ</rt></ruby>からの<ruby>喜<rt>よろこ</rt></ruby>びが<ruby>訪<rt>おとず</rt></ruby>れるよ",
    "<ruby>今日<rt>きょう</rt></ruby>のあなたは<ruby>特別<rt>とくべつ</rt></ruby><ruby>幸運<rt>こううん</rt></ruby>！",
    "<ruby>願<rt>ねが</rt></ruby>いが<ruby>次々<rt>つぎつぎ</rt></ruby><ruby>叶<rt>かな</rt></ruby>うよ",
    "<ruby>新<rt>あたら</rt></ruby>しいことに<ruby>挑戦<rt>ちょうせん</rt></ruby>してみよう！",
    "<ruby>友達<rt>ともだち</rt></ruby>と<ruby>仲良<rt>なかよ</rt></ruby>く<ruby>過<rt>す</rt></ruby>ごせるよ",
    "いっぱい<ruby>笑<rt>わら</rt></ruby>って<ruby>過<rt>す</rt></ruby>ごそう！",
    "<ruby>新<rt>あたら</rt></ruby>しい<ruby>発見<rt>はっけん</rt></ruby>がある<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>皆<rt>みな</rt></ruby>があなたを<ruby>応援<rt>おうえん</rt></ruby>してるよ",
    "<ruby>楽<rt>たの</rt></ruby>しい<ruby>驚<rt>おどろ</rt></ruby>きがあるよ！",
    "<ruby>好<rt>す</rt></ruby>きなことが<ruby>上手<rt>じょうず</rt></ruby>くいくよ",
    "<ruby>気持<rt>きも</rt></ruby>ちが<ruby>安定<rt>あんてい</rt></ruby>する<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>幸<rt>しあわ</rt></ruby>せな<ruby>気持<rt>きも</rt></ruby>ちでいっぱいになるよ！",
    "<ruby>自分<rt>じぶん</rt></ruby>を<ruby>信<rt>しん</rt></ruby>じて<ruby>進<rt>すす</rt></ruby>もう！",
    "<ruby>素敵<rt>すてき</rt></ruby>な<ruby>夢<rt>ゆめ</rt></ruby>が<ruby>見<rt>み</rt></ruby>られるよ",
    "<ruby>皆<rt>みな</rt></ruby>と<ruby>笑顔<rt>えがお</rt></ruby>で<ruby>過<rt>す</rt></ruby>ごせる<ruby>日<rt>ひ</rt></ruby>だよ",
    "<ruby>素敵<rt>すてき</rt></ruby>な<ruby>贈<rt>おく</rt></ruby>りものが<ruby>届<rt>とど</rt></ruby>くかも！",
]

FORTUNES_EN = [
    "Today might bring you some unexpected income!",
    "Good news is coming your way!",
    "You will spend wonderful time with someone special.",
    "A wish you made may come true today.",
    "You might meet someone new and exciting.",
    "Your luck is rising! Everything will go smoothly.",
    "A healthy and happy day awaits you.",
    "Lots of fun and joy will visit you.",
    "Keep smiling — happiness follows you.",
    "Fortune will find you today.",
    "You’re getting closer to your dreams.",
    "Peace and calm will fill your heart.",
    "Unexpected luck will come your way!",
    "A wish is likely to be granted soon.",
    "Your relationships will improve.",
    "A pleasant surprise is waiting for you.",
    "Your financial luck is looking up.",
    "Your efforts will pay off today.",
    "Expressing gratitude will bring good vibes.",
    "Your smile will make you shine.",
    "You might find a new hobby.",
    "Your adventurous spirit will awaken.",
    "You will feel lighter and happier today.",
    "Your friendship bonds will deepen.",
    "Your love luck is strong right now.",
    "Don’t give up on your dreams.",
    "Happiness will keep coming your way.",
    "Stay positive — it’s important!",
    "Good news is on its way.",
    "You will be full of energy today.",
    "Now is the perfect time to grab a chance.",
    "Take time to relax and recharge.",
    "You will feel many happy moments.",
    "Wishes are more likely to come true today.",
    "You will grow emotionally.",
    "Smiling when meeting people will bring luck.",
    "You will learn something new today.",
    "You might meet someone special.",
    "Your heart will feel peaceful.",
    "A fateful encounter may be near.",
    "Your motivation will be high.",
    "Happy news is on its way.",
    "Never forget to feel gratitude.",
    "Your smile will attract good fortune.",
    "Good vibes are flowing your way.",
    "New challenges will succeed.",
    "Fun events are waiting for you.",
    "Fortune will smile upon you.",
    "Joy from the heart will visit you.",
    "Today is especially lucky for you.",
    "Your wishes will come true one after another.",
    "Try new challenges today!",
    "You will get along well with friends.",
    "Laugh a lot and enjoy your day!",
    "Discover something new today.",
    "Everyone supports you.",
    "You will be pleasantly surprised.",
    "Things you like will go well.",
    "Your feelings will be calm and steady.",
    "Your heart will be full of happiness.",
    "Believe in yourself and move forward.",
    "You will have sweet dreams.",
    "Spend the day smiling with everyone.",
    "A wonderful gift may arrive for you."
];

@app.get("/fortune")
def get_fortune(language: str = Query("ja", regex="^(ja|en)$")):
    if language == "en":
        return {"fortune": random.choice(FORTUNES_EN)}
    else:
        return {"fortune": random.choice(FORTUNES_JA)}
